# -*- coding: utf-8 -*-
"""Customer_Purchase_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VC7abviHYZZZyXI8cBENVrxhD-upPV79
"""

print(df[['discount', 'profit']].corr())

sns.scatterplot(x='discount', y='profit', data=df, alpha=0.5)
plt.title("Discount vs Profit")
plt.show()