# -*- coding: utf-8 -*-
"""Customer_Purchase_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VC7abviHYZZZyXI8cBENVrxhD-upPV79
"""

region_sales_profit = df.groupby('region')[['sales', 'profit']].sum().sort_values(by='sales', ascending=False)
print(region_sales_profit)

region_sales_profit.plot(kind='bar', figsize=(8,5))
plt.title("Sales & Profit by Region")
plt.ylabel("Amount")
plt.show()