# -*- coding: utf-8 -*-
"""Customer_Purchase_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VC7abviHYZZZyXI8cBENVrxhD-upPV79
"""

segment_sales_profit = df.groupby('segment')[['sales', 'profit']].sum().sort_values(by='sales', ascending=False)
print(segment_sales_profit)

segment_sales_profit.plot(kind='bar', figsize=(8,5), color=['teal', 'orange'])
plt.title("Sales & Profit by Segment")
plt.ylabel("Amount")
plt.show()