# -*- coding: utf-8 -*-
"""Customer_Purchase_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VC7abviHYZZZyXI8cBENVrxhD-upPV79
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("Sample - Superstore.csv", encoding='latin1')
df.shape, df.head()