# -*- coding: utf-8 -*-
"""Customer_Purchase_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VC7abviHYZZZyXI8cBENVrxhD-upPV79
"""

# Remove duplicates & missing
df.drop_duplicates(inplace=True)
df.dropna(inplace=True)

# Standardize column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

# Convert dates
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])

# Calculate shipping days
df['shipping_days'] = (df['ship_date'] - df['order_date']).dt.days

# Drop irrelevant columns
df.drop(columns=['row_id', 'postal_code'], errors='ignore', inplace=True)

df.info()
df.head()