# -*- coding: utf-8 -*-
"""Customer_Purchase_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VC7abviHYZZZyXI8cBENVrxhD-upPV79
"""

subcat_sales_profit = df.groupby('sub-category')[['sales', 'profit']].sum().sort_values(by='sales', ascending=False).head(5)
print(subcat_sales_profit)

subcat_sales_profit.plot(kind='bar', figsize=(10,5))
plt.title("Top 5 Sub-categories by Sales")
plt.ylabel("Amount")
plt.show()