# -*- coding: utf-8 -*-
"""Customer_Purchase_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VC7abviHYZZZyXI8cBENVrxhD-upPV79
"""

avg_shipping = df['shipping_days'].mean()
print(f"Average Shipping Days: {avg_shipping:.2f}")