# -*- coding: utf-8 -*-
"""Customer_Purchase_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VC7abviHYZZZyXI8cBENVrxhD-upPV79
"""

category_sales_profit = df.groupby('category')[['sales', 'profit']].sum().sort_values(by='sales', ascending=False)
print(category_sales_profit)

category_sales_profit.plot(kind='bar', figsize=(8,5), color=['purple', 'green'])
plt.title("Sales & Profit by Category")
plt.ylabel("Amount")
plt.show()